data:
  mongodb:
    uri: mongodb://localhost:27017/psynea

spring:
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true

  kafka:
    bootstrap-servers: 192.168.133.129:9092
    consumer:
      auto-offset-reset: earliest