data:
  mongodb:
    uri: mongodb://localhost:27017/psynea

spring:
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true